---

- name: Install rsyslog_package
  ansible.builtin.apt:
    name: "{{ rsyslog_package }}"
    state: present

- name: Install rsyslog_extar_packages
  ansible.builtin.apt:
    name: "{{ rsyslog_extar_packages }}"
    state: present

- name: Create /etc/default/rsyslog
  # XXX this taks is here for completeness. but the unit file for rsyslog on
  # Ubuntu does not read /etc/default/rsyslog
  ansible.builtin.template:
    src: default.j2
    dest: /etc/default/rsyslog
    mode: "0644"

- name: Enable rsyslog_service
  ansible.builtin.service:
    name: "{{ rsyslog_service }}"
    enabled: yes
